### PR TITLE
fix: toggle switch accessibility labels 

### LINKED ISSUE #1143: Toggle button is not identified in Voice Control
Toggle button is not identified when voice control in turned on. 

this issue appears in
- toggle button in the biometrics screen
- toggle buttons in developer options screen
- others? It might appear for all toggles. 

build: 905
devices: iOS

### PR DESCRIPTION
**Pull request by jleach**
# Summary of Changes

Fix toggle (switch) accessibility labels so they are read and displayed properly.

Screenshot 2023-06-07 at 8 26 48 AM

# Related Issues

Fixes bcgov/bc-wallet-mobile#1143

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

File: packages/legacy/core/App/screens/Developer.tsx [hunk 1]
```diff
@@ -65,13 +65,11 @@ const Developer: React.FC = () => {
...
+          <Text accessible={false} style={styles.settingLabelText}>
+            {t('Verifier.UseVerifierCapability')}
+          </Text>
         </View>
-        <TouchableWithoutFeedback
-          style={styles.settingSwitchContainer}
-          accessibilityLabel={t('Verifier.Toggle')}
-          accessibilityRole={'switch'}
-        >
+        <Pressable style={styles.settingSwitchContainer} accessibilityLabel={'xx'} accessibilityRole={'switch'}>
```
Comment (bryce-mcmath) [inline packages/legacy/core/App/screens/Developer.tsx]: why the label 'xx'?

Comment (jleach) [reply packages/legacy/core/App/screens/Developer.tsx]: Ahh. Developer testing. Will fix.

**Review by bryce-mcmath — APPROVED** [review]
