### PR TITLE
fix: grab credential name from proof restriction

### LINKED ISSUE #662: Incorrect credential name in proof if credential not found in wallet
As a holder, if the verifier issues me a proof request for a credential I don't have available in the wallet, I should be able to see the name of the credential being requested.  
  
currently the proof attribute group name is being used to display the credential name in bifold. This isn't guaranteed to be the same as the credential name.  
  
Parsing the credential name from the attribute/predicate proof restrictions is a more reliable method of getting the credential name.

### PR DESCRIPTION
**Pull request by wadeking98**
# Summary of Changes

Previously, if a credential for a proof request wasn't in the wallet, the wallet would display the requested attributes/predicate group name as the credential name. This functionality changes the behaviour so it first looks to see if there are any restrictions to cred_def_id, schema_name, or schema_id and grabs the name of the credential from there  

# Related Issues

Resolves: https://github.com/hyperledger/aries-mobile-agent-react-native/issues/662

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

**Review by bryce-mcmath — DISMISSED** [review]

File: core/App/screens/ProofRequest.tsx [hunk 1]
```diff
@@ -194,11 +196,21 @@ const ProofRequest: React.FC<ProofRequestProps> = ({ navigation, route }) => {
...
+        )
+        if (credNamesInAttrs.includes(startCase(credName))) {
+          credFound = true
+          return
+        }
+      })
+      return credFound
+    }
+
+    return typeof retrievedCredentials !== 'undefined' && Object.values(fields).every((c) => c.length > 0)
```
Comment (bryce-mcmath) [inline core/App/screens/ProofRequest.tsx]: I know you didn't write this line, but should we also be checking for `null`, not just undefined?

**Review by bryce-mcmath — COMMENTED** [review]
Just one small question, otherwise still LGTM

File: core/App/screens/ProofRequest.tsx (hunk 1 above)
Comment (wadeking98) [reply core/App/screens/ProofRequest.tsx]: we could use it as a falsy value and that way it would catch undefined, null, and the empty string

File: core/App/screens/ProofRequest.tsx [hunk 2]
```diff
@@ -194,11 +196,21 @@ const ProofRequest: React.FC<ProofRequestProps> = ({ navigation, route }) => {
...
+        )
+        if (credNamesInAttrs.includes(startCase(credName))) {
+          credFound = true
+          return
+        }
+      })
+      return credFound
+    }
+
+    return !typeof retrievedCredentials && Object.values(fields).every((c) => c.length > 0)
```
Comment (bryce-mcmath) [inline core/App/screens/ProofRequest.tsx]: should this just be `return retrievedCredentials && Object.values(fields).every((c) => c.length > 0)`?

the `typeof` will give a non-empty string in almost every case, no?

**Review by bryce-mcmath — CHANGES_REQUESTED** [review]

File: core/App/screens/ProofRequest.tsx (hunk 2 above)
Comment (wadeking98) [reply core/App/screens/ProofRequest.tsx]: yes, my bad

Comment (wadeking98) [reply core/App/screens/ProofRequest.tsx]: okay fixed it

**Review by amanji — DISMISSED** [review]

**Review by bryce-mcmath — APPROVED** [review]
