### PR TITLE
fix: no screen read settings icons

### LINKED ISSUE #1094: Icons in Menu aren't marked as decorative/null
Screen readers detect the icons in the settings but don't read anything.

### PR DESCRIPTION
**Pull request by jleach**
# Summary of Changes

Disable accessibility on the menu header icons in Settings and add accessibility role to better indicate what is being read.

# Related Issues

Fixed bcgov/bc-wallet-mobile#1094, bcgov/bc-wallet-mobile#1139

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

File: packages/legacy/core/App/screens/Settings.tsx [hunk 1]
```diff
@@ -224,8 +224,10 @@ const Settings: React.FC<SettingsProps> = ({ navigation }) => {
 
   const SectionHeader: React.FC<{ icon: string; title: string }> = ({ icon, title }) => (
     <View style={[styles.section, styles.sectionHeader]}>
-      <Icon name={icon} size={24} style={{ marginRight: 10, color: SettingsTheme.iconColor }} />
-      <Text style={[TextTheme.headingThree, { flexShrink: 1 }]}>{title}</Text>
+      <Icon accessible={false} name={icon} size={24} style={{ marginRight: 10, color: SettingsTheme.iconColor }} />
+      <Text accessibilityRole={'header'} style={[TextTheme.headingThree, { flexShrink: 1 }]}>
```
Comment (bryce-mcmath) [inline packages/legacy/core/App/screens/Settings.tsx:228]: This might be pedantic but I think these elements are headings, not headers

Comment (jleach) [reply packages/legacy/core/App/screens/Settings.tsx:228]: I think that's a more accurate word but I don't have "heading" as an accessibility role and the description seems to fit as a "content section".

Docs: **header** Used when an element acts as a header for a content section (e.g. the title of a navigation bar).

**Review by bryce-mcmath — DISMISSED** [review]

**Review by bryce-mcmath — APPROVED** [review]
