### PR TITLE
fix: reset navigation stack for problematic screens

### LINKED ISSUE #460: Back button to splash screen should be removed
Introduced with initialization refactor. A user can go back to the Splash screen with no way to exit without closing app.

### PR DESCRIPTION
**Pull request by bryce-mcmath**
# Summary of Changes

Resetting the navigation stack when navigating from problematic screens that we don't want users to be able to navigate back to (either with swipe back on iOS or hardware back button on Android)

# Related Issues

Resolves #460 

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

File: core/App/screens/PINCreate.tsx [hunk 1]
```diff
@@ -102,7 +103,12 @@ const PINCreate: React.FC<PINCreateProps> = ({ setAuthenticated }) => {
       })
 
       // TODO: Navigate back if in settings
```
Comment (jleach) [inline core/App/screens/PINCreate.tsx:105]: Is the TODO needed?

**Review by jleach — APPROVED** [review]
