### PR TITLE
fix: tab bar layout on ipad

### LINKED ISSUE #1428: Notification badge location wrong on iPad
As per the image below when on displayed on an iPad the notification badge is not located in the correct place:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazF1IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8550ca33d14c711623ecf1d64fcba23b6505c483/IMG_1886.PNG)

### PR DESCRIPTION
**Pull request by jleach**
# Summary of Changes

Fix an issue where the notification badge on the iPad is misaligned.

# Related Issues

Fixes bcgov/bc-wallet-mobile#1428

# Pull Request Checklist

Tick all boxes below to demonstrate that you have completed the respective task. If the item does not apply to your this PR **check it anyway** to make it apparent that there's nothing to do.

- [x] All commits contain a DCO `Signed-off-by` line (we use the [DCO GitHub app](https://github.com/apps/dco) to enforce this);
- [x] Updated LICENSE-3RD-PARTY.md for any added dependencies or vendored components;
- [x] Updated documentation as needed for changed code and new or modified features;
- [x] Added sufficient [tests](../__tests__/) so that overall code coverage is not reduced.

If you have _any_ questions to _any_ of the points above, just **submit and ask**! This checklist is here to _help_ you, not to deter you from contributing!

Pro Tip 🤓

- Read our [contribution guide](../CONTRIBUTING.md) at least once; it will save you a few review cycles!
- Your PR will likely not be reviewed until all the above boxes are checked and all automated tests have passed.

_PR template adapted from the Python attrs project._

### CODE REVIEW

File: packages/legacy/core/App/navigators/TabStack.tsx [hunk 1]
```diff
@@ -53,11 +63,11 @@ const TabStack: React.FC = () => {
               <AttachTourStep tourID={TourID.HomeTour} index={1}>
                 <View style={{ ...TabTheme.tabBarContainerStyle, justifyContent: showLabels ? 'flex-end' : 'center' }}>
                   <Icon name={focused ? 'message-text' : 'message-text-outline'} color={color} size={30} />
+
                   {showLabels && (
                     <Text
                       style={{
                         ...TabTheme.tabBarTextStyle,
-                        color: focused ? TabTheme.tabBarActiveTintColor : TabTheme.tabBarInactiveTintColor,
```
Comment (bryce-mcmath) [inline packages/legacy/core/App/navigators/TabStack.tsx]: Just curious, why did we get rid of this line?

Comment (jleach) [reply packages/legacy/core/App/navigators/TabStack.tsx]: I see it locally. Looking to see why.

Comment (jleach) [reply packages/legacy/core/App/navigators/TabStack.tsx]: Fixed.

**Review by bryce-mcmath — APPROVED** [review]
